baseURL: 'https://hnjae.github.io/'
languageCode: 'ko-KR'
defaultContentLanguage: 'ko'
defaultContentLanguageInSubdir: false
hasCJKLanguage: true
rssLimit: '1000'
title: "hnjae's wiki"
theme: "PaperMod"
uglyurls: true

languages:
  ko:
    contentDir: content/ko
    languageCode: ko-KR
    languageName: í•œêµ­ì–´
    permalinks:
      page:
        wiki: /wiki/:filename/
        blog: /blog/:year/:slug/
      section:
        wiki: /wiki/
        blog: /blog/
    weight: 1
  # en:
  #   contentDir: content/en


menu:
  main:
    - identifier: wiki
      name: wiki
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 90


# enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    # - :git
    # - date
    # - publishDate

params:
  author: "Hyunjae Kim"
  # DateFormat: "2006-01-02T15:04:05-0700"
  DateFormat: "2006-01-02"
  showtoc: true
  tocopen: true
  defaultTheme: auto
  defaultThemeToggle: true
  homeInfoParams:
    Title: ê°œì¸ ìœ„í‚¤ì…ë‹ˆë‹¤ ğŸ‘‹
    # Content:
  socialIcons:
    - name: github
      url: "https://github.com/hnjae"
  hideAuthor: true
  cover:
    hiddenInList: true
  mainSections:
    - wiki

markup:
  asciidocExt:
    preserveTOC: false # default false
    backend: html5
    safeMode: unsafe
    attributes:
      source-highlighter:  "rouge"
      rouge-css: "style"
      rouge-style: "thankful_eyes"
      stem: "latexmath"
      icons: "font"
    #   hide-uri-scheme: true@ # hide http(s) in link / @ means ok to override
    # extensions:

security:
  exec:
    allow:
      - "^asciidoctor$"
  # http:
  #   methods:
  #     - '(?i)GET|POST'
  #   urls:
  #     - '.*'
