baseURL: 'https://hnjae.github.io/'
languageCode: 'ko-KR'
defaultContentLanguage: 'ko'
defaultContentLanguageInSubdir: false
hasCJKLanguage: true
rssLimit: '1000'
title: "hnjae's wiki"
theme: "PaperMod"
uglyurls: false

languages:
  ko:
    contentDir: content/ko
    languageCode: ko-KR
    languageName: í•œêµ­ì–´
    permalinks:
      page:
        pages: /wiki/:slug/
        blog: /blog/:year/:slug/
      section:
        wiki: /pages/
        blog: /blog/
    weight: 1
  # en:
  #   contentDir: content/en


menu:
  main:
    - identifier: wiki
      name: wiki
      url: /
      weight: 10
    - identifier: blog
      name: blog
      url: /blog/
      weight: 20
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 90


# enableGitInfo: true

frontmatter:
  lastmod:
    - lastmod
    # - :git
    # - date
    # - publishDate

params:
  author: "Hyunjae Kim"
  # DateFormat: "2006-01-02T15:04:05-0700"
  DateFormat: "2006-01-02"
  showtoc: true
  tocopen: true
  defaultTheme: auto
  defaultThemeToggle: true
  homeInfoParams:
    Title: ê°œì¸ ìœ„í‚¤ì…ë‹ˆë‹¤ ğŸ‘‹
  socialIcons:
    - name: github
      url: "https://github.com/hnjae"
  hideAuthor: true
  cover:
    hiddenInList: true
